import { ClerkProvider } from "@clerk/nextjs";
import '../globals.css';
import { Montserrat } from "next/font/google";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const montserrat = Montserrat({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${montserrat.className} bg-dark-1`}>
          <div className="w-full flex justify-center items-center min-h-screen">
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  )
}
