import { ClerkProvider } from "@clerk/nextjs";
import '../globals.css';
import { Montserrat } from "next/font/google";
import PublicNavBar from "@/components/shared/PublicNavBar";
import PublicFooter from "@/components/shared/PublicFooter";
import SkeletonForm from "@/components/shared/SkeletonForm";

import { Suspense } from "react";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const montserrat = Montserrat({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${montserrat.className} bg-dark-1`}>
          <div className="w-full flex justify-center items-center min-h-screen">
          <div className="flex w-full flex-grow flex-col items-center bg-light-4">
      <PublicNavBar />
      <Suspense fallback={<SkeletonForm />}>
            {children}
          </Suspense>
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  )
}
